# Generated by Django 3.2.16 on 2022-11-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='map_url',
            new_name='map_embed',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='rating',
        ),
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='bath',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='bbq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='central_heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='cot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='dog_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='fireplace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='hob',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='hot_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='oven',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='shower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='washing_machine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='no_sleeps',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='listing',
            name='region',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
    ]
