# Generated by Django 3.2.16 on 2022-11-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lead_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='lead_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
