# Generated by Django 3.2.16 on 2022-11-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20221101_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bath',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bbq',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='central_heating',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='cot',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='dog_friendly',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='fireplace',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='fridge',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='hob',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='hot_water',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='oven',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='shower',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='tv',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='washing_machine',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='wheelchair_accessible',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='wifi',
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_friendly', models.BooleanField(default=False)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('hot_water', models.BooleanField(default=False)),
                ('central_heating', models.BooleanField(default=False)),
                ('fireplace', models.BooleanField(default=False)),
                ('bath', models.BooleanField(default=False)),
                ('shower', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('hob', models.BooleanField(default=False)),
                ('oven', models.BooleanField(default=False)),
                ('fridge', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('bbq', models.BooleanField(default=False)),
                ('cot', models.BooleanField(default=False)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='listings.listing')),
            ],
        ),
    ]
