# Generated by Django 3.2.16 on 2022-11-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20221101_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.DeleteModel(
            name='Facilities',
        ),
        migrations.AddField(
            model_name='listing',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='listings.Facility'),
        ),
    ]
