# Generated by Django 3.2.16 on 2022-11-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20221101_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='font_awesome_class',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
