# Generated by Django 3.2.16 on 2022-12-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_facility_font_awesome_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=2, null=True),
        ),
    ]
