# Generated by Django 3.2.16 on 2022-11-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
