# Generated by Django 3.2.16 on 2022-12-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
