# Generated by Django 3.2.16 on 2022-12-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
